    
    <br>
    <div class="col-11 m-auto">
        <span class="fs-3">Usuários</span >
        <br>
        Total de Registros Encontrados: <?php echo count($usuarios); ?>

        <!--Alertas-->
<!--        <div id="alertBoxSucesso" name="alertBoxSucesso" class="row">
                <div class="col-lg-12">
                        <div class="alert alert-success fade show" role="alert">
                                <div class="text-end" style="width:100%"><a class="btn btn-success btn-sm" id="closeAlertBoxSucesso" name="closeAlertBoxSucesso"><strong>X</strong></a></div>
                                <span>
                                        Mensagem
                                </span>
                        </div>
                </div>
        </div>
        <div id="alertBoxErro" name="alertBoxErro" class="row">
                <div class="col-lg-12">
                        <div class="alert alert-danger fade show" role="alert">
                                <div class="text-end" style="width:100%"><a class="btn btn-danger btn-sm" id="closeAlertBoxErro" name="closeAlertBoxErro"><strong>X</strong></a></div>
                                <span>
                                        Mensagem
                                </span>
                        </div>
                </div>
        </div>-->
        <!--End Alertas-->

        <div id="searchBox" name="searchBox" class="form-group text-end">
                <p>
                <form name="formSearch" id="formSearch" method="post" action="<?php echo $this->url('usuario', ['action'=>'index']); ?>" style="display:inline">

                        <div class="input-group">
                                <span style="width:15%" class="input-group-text">Nome</span>
                                <input type="text" id="nome" name="nome" class="form-control" value="">
                                <a class="btn btn-secondary" id="pesquisar" name="pesquisar" onclick="document.getElementById('formSearch').submit();">
                                    <i class="bi bi-search"></i>&nbsp;Pesquisar
                                </a>
                        </div>

                </form>
                </p>
        </div>

        <table class="table table-sm table-striped table-borderless">
            <thead class="table-dark">
                <tr>
                    <td style="width:10%" class="align-middle text-center">ID</td>
                    <td style="width:25%" class="align-middle text-center">Nome</td>
                    <td style="width:25%" class="align-middle text-center">Email</td>
                    <td style="width:15%" class="align-middle text-center">Senha</td>
                    <td style="width:25%" class="text-end">
                        <a id="filtrar" name="filtrar"  class="btn btn-secondary">
                            <i class="bi bi-funnel-fill"></i>&nbsp;Filtrar
                        </a>
                        <a class="btn btn-success" href="<?php echo $this->url('usuario', ['action' => 'cadastrar']); ?>">
                            <i class="bi bi-person-plus-fill"></i>&nbsp;Cadastrar
                        </a>
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <?php if(count($usuarios) <= 0){ ?>
                    <td colspan="5" class="align-middle text-center">Não existem dados cadastrados.</td>
                    <?php } ?>
                </tr>
                <?php foreach($usuarios as $usuario): ?>
                <tr>
                    <td style="width:10%" class="align-middle text-center"><?php echo $usuario->getId(); ?></td>
                    <td style="width:25%" class="align-middle text-center"><?php echo $usuario->getNome(); ?></td>
                    <td style="width:25%" class="align-middle text-center"><?php echo $usuario->getEmail(); ?></td>
                    <td style="width:15%" class="align-middle text-center"><?php echo base64_decode($usuario->getSenha()); ?></td>
                    <td style="width:25%" class="text-end">
                        <a class="btn btn-primary" href="<?php echo $this->url('usuario', ['action' => 'editar', 'id' => $usuario->getId()]); ?>">
                            <i class="bi bi-pencil-square"></i>&nbsp;Editar
                        </a>
                        <a class="btn btn-danger" href="<?php echo $this->url('usuario', ['action' => 'deletar', 'id' => $usuario->getId()]); ?>">
                            <i class="bi bi-trash-fill"></i>&nbsp;Deletar
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="d-flex justify-content-center">
        <!-- paginação-->
        </div>
        
    </div>
