<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
	<br>
	<div class="col-11 m-auto">
            <span class="fs-3">Usuários</span >
            <br>
            Total de Registros Encontrados:


            <!--Alertas-->
            <div id="alertBox" name="alertBox" class="row">
                    <div class="col-lg-12">
                            <div class="alert alert-success fade show" role="alert">
                                    <div class="text-end" style="width:100%"><a class="btn btn-success btn-sm" id="closeAlertBox" name="closeAlertBox"><strong>X</strong></a></div>
                                    <span>
                                            Mensagem
                                    </span>
                            </div>
                    </div>
            </div>
            <!--End Alertas-->


            <div id="searchBox" name="searchBox" class="form-group text-end">
                    <p>
                    <form name="formSearch" id="formSearch" method="post" action="" style="display:inline">

                            <div class="input-group">
                                    <span style="width:15%" class="input-group-text">Nome</span>
                                    <input type="text" id="nome" name="nome" class="form-control" value="">
                                    <a class="btn btn-secondary" id="pesquisar" name="pesquisar" onclick="document.getElementById('formSearch').submit();">
                                    Pesquisar
                                    </a>
                            </div>
							
                    </form>
                    </p>
            </div>

            <table class="table table-sm table-striped table-borderless">
                <thead class="table-dark">
                    <tr>
                        <td style="width:10%" class="align-middle text-center">ID</td>
                        <td style="width:25%" class="align-middle text-center">Nome</td>
                        <td style="width:25%" class="align-middle text-center">Email</td>
                        <td style="width:15%" class="align-middle text-center">Senha</td>
                        <td style="width:25%" class="text-end">
                            <a id="filtrar" name="filtrar"  class="btn btn-secondary">
                                Filtrar
                            </a>
                            <a class="btn btn-success" href="">
                                Cadastrar
                            </a>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
<!--                            @if(count($aluno) <= 0)-->
                        <td colspan="5" class="align-middle text-center">Não existem dados cadastrados.</td>
<!--                            @endif-->
                    </tr>
<!--			@foreach($aluno as $alunos)-->
                    <tr>
                        <td style="width:10%" class="align-middle text-center"></td>
                        <td style="width:25%" class="align-middle text-center"></td>
                        <td style="width:25%" class="align-middle text-center"></td>
                        <td style="width:15%" class="align-middle text-center"></td>
                        <td style="width:25%" class="text-end">
                            <a class="btn btn-primary" href="">
                                Editar
                            </a>
                            <form name="formDelete" id="formDelete" method="post" action="" style="display:inline">
                                <a class="btn btn-danger" onclick="document.getElementById('formDelete').submit();">
                                    Deletar
                                </a>							
                            </form>
                        </td>
                    </tr>
<!--                        @endforeach-->
                </tbody>
            </table>

            <div class="d-flex justify-content-center">
<!--            paginação-->
            </div>
	</div>
