<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-7">Seja bem vindo à avaliação prática para a vaga de programador PHP.</h1>
    <br>
    <p>
        Este projeto encontra-se disponível num repositório online do GitHub
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/duducavalcanti/avaliacao-webanalisys" target="_blank">
        Acessar Projeto &raquo;
    </a>
</div>
